### ISSUE TITLE
Correction about counting bf.

### ISSUE THREAD

**Issue by dasfex** [mavam/libbf#51]
Should we decrement count if one of bits are equal to zero?

**Comment by mavam** [comment]
I'm not sure what you propose exactly. Currently, the algorithm decrements a cell value iff it is non-zero. It is a for-loop, however, so if the first cell is already zero and subsequent ones not, then the algorithms stops immediately. This doesn't affect correctness, because the minimum is used when computing the count.

What should be the expected behavior in your opinion?

**Comment by dasfex** [comment]
I say about that fact that you stop only the first cell value is zero, as I understand. I suggest firstly take sure that any of cell values is non-zero and if all correct to decrement. I agree that we are use minimum so everything correct. But if you decrement and I am not, can we put this down to the fact that we don't necessarily get a 100% correct result? (sorry for poor eng)

**Comment by mavam** [comment]
I think that's also a valid approach and slight less aggressive. I haven't had a chance to look around, but I wouldn't be surprised if someone sat down and proved the bounds analytically of the various options.

If there is some evidence that it makes sense to have multiple approaches, we can make the decrement algorithm a policy.
